name: my-vault-cluster

services:
  vault-server1:
    image: hashicorp/vault:1.17
    hostname: vault-server1
    container_name: vault-server1
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    networks:
      - vault-cluster-network
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
    volumes:
      - ./vault-server1/config:/vault/config # mapping storage on computer
      - vault1-filestorage:/vault/file # mapping storage on docker volume
      - ./vault-server1/logs:/vault/logs # mapping storage on computer
    entrypoint: vault server -config=/vault/config/config.hcl

  vault-server2:
    image: hashicorp/vault:1.17
    hostname: vault-server2
    container_name: vault-server2
    ports:
      - "8202:8200"
    cap_add:
      - IPC_LOCK
    networks:
      - vault-cluster-network
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
    volumes:
      - ./vault-server2/config:/vault/config # mapping storage on computer
      - vault2-filestorage:/vault/file # mapping storage on docker volume
      - ./vault-server2/logs:/vault/logs # mapping storage on computer
    entrypoint: vault server -config=/vault/config/config.hcl

  vault-server3:
    image: hashicorp/vault:1.17
    hostname: vault-server3
    container_name: vault-server3
    ports:
      - "8204:8200"
    cap_add:
      - IPC_LOCK
    networks:
      - vault-cluster-network
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
    volumes:
      - ./vault-server3/config:/vault/config # mapping storage on computer
      - vault3-filestorage:/vault/file # mapping storage on docker volume
      - ./vault-server3/logs:/vault/logs # mapping storage on computer
    entrypoint: vault server -config=/vault/config/config.hcl

networks:
  vault-cluster-network:
    driver: bridge

volumes:
  vault1-filestorage:
  vault2-filestorage:
  vault3-filestorage: